import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(GeistSans.variable, GeistSans.className)}>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased bg-sky-400"
        )}
      >
        {children}
      </body>
    </html>
  );
}
